
pipeline{agent anystages{    stage("build"){        steps{            echo 'building our app'        }    }    stage("test"){        steps{            echo 'testing'        }    }    stage("deploy"){        steps{            echo 'deploying'        }    }}}
 like 3

